homeassistant:
  customize: {}

input_datetime:
  preheat_start:
    name: Preheat Start
    has_date: false
    has_time: true
  comfort_time:
    name: Comfort Time
    has_date: false
    has_time: true

input_number:
  preheat_min_lead:
    name: Min Preheat Lead (min)
    min: 0
    max: 240
    step: 1
    unit_of_measurement: min
    icon: mdi:timer-outline
  preheat_max_lead:
    name: Max Preheat Lead (min)
    min: 0
    max: 480
    step: 1
    unit_of_measurement: min
    icon: mdi:timer-cog
  preheat_unoccupied_cap:
    name: Unoccupied Lead Cap (min)
    min: 0
    max: 240
    step: 1
    unit_of_measurement: min
    icon: mdi:home-off
  hvac_comfort_start_target_temp:
    name: HVAC Comfort Target Temperature
    min: 50
    max: 80
    step: 0.5
    unit_of_measurement: "°F"
    icon: mdi:thermometer
    

input_text:
  furnace_model_json:
    name: Furnace Model (JSON)
    max: 255
input_boolean:
  preheat_active:
    name: Preheat Active
    icon: mdi:fire-alert
